#include "LibInfo.h"
#include "DATAWDataWidget.h"

#include <WDataNavWidget.h>

#include <AWPalWidget.h>
#include <AWPanWidget.h>

#include <DATAConnection.h>
#include <DATAStatement.h>

DATAWDataWidget::DATAWDataWidget( AWObject *pObject, QWidget *pParent, DATAConnection *p, const QString &stringCatalog, const QString &stringSchema, const QString &stringTable  )
: AWEditorWidget( pObject, pParent )
{
// printf( "[%s][%s][%d] [%s][%s][%s]\n", __FILE__, __FUNCTION__, __LINE__, stringCatalog.toUtf8().constData(), stringSchema.toUtf8().constData(), stringTable.toUtf8().constData() );
    setObjectName( metaObject()->className() );
    pConnection         = p;
    this->stringCatalog = stringCatalog;
    this->stringSchema  = stringSchema;
    this->stringTable   = stringTable;
    nRows                   = 0;
    nMaxRows                = 5000;
            
    QToolBar *pToolBar = addToolBar( "Navigation" );
    WDataNavWidget *pNavigation = new WDataNavWidget( pToolBar );
    pToolBar->addWidget( pNavigation );

    ptableResults = new QTableWidget();
    ptableResults->setRowCount( 1 );
    setCentralWidget( ptableResults );

    doLoadState();

    // no connection no joy
    if ( !pConnection ) return;
    if ( !pConnection->isConnected() ) return;

    // no rowid no edit
    listRowID   = getRowID();
    listColumns = getColumns();

    // build complete column list including any 'hidden' RowID
    listColumnsQuery = listColumns;
    foreach ( const QString &s, listRowID )
    {
        if ( !listColumnsQuery.contains( s ) ) listRowID.insert( 0, s );
    }

    // build query string specifiying columns ex0plicitly
    stringQuery = "SELECT ";
    bool bFirst = true;
    foreach ( const QString &s, listColumnsQuery )
    {
        if ( !bFirst ) stringQuery += ", "; else bFirst = false;
        stringQuery += s;
    }
    stringQuery += " FROM " + stringTable;

// printf( "[%s][%s][%d] %s\n", __FILE__, __FUNCTION__, __LINE__, stringQuery.toUtf8().constData() );
    //
    pStatement = pConnection->getExecute( stringQuery );
    if ( !pStatement ) return;                                                      
    doResultGUIGrid();
}


DATAWDataWidget::~DATAWDataWidget()
{
//    doSaveState();
    if ( pStatement ) delete pStatement;
}

AWPalWidget *DATAWDataWidget::getPalWidget()
{
    if ( pPalWidget ) return pPalWidget;
    pPalWidget = new AWPalWidget( this, nullptr );
    return pPalWidget;
}

AWPanWidget *DATAWDataWidget::getPanWidget()
{
    if ( pPanWidget ) return pPanWidget;
    pPanWidget = new AWPanWidget( this, nullptr );
    return pPanWidget;
}

QStringList DATAWDataWidget::getRowID()
{
    QStringList     listColumns;
    DATAStatement * pStatement = pConnection->getSpecialColumns( stringCatalog, stringSchema, stringTable );
    if ( !pStatement ) return listColumns;

    SQLRETURN n = pStatement->doFetch();
    while ( SQL_SUCCEEDED( n ) )
    {
        QString stringColumn = pStatement->getData( 2 ).toString();
        // abort if column name missing
        if ( stringColumn.isEmpty() )
        {
            delete pStatement;
            listColumns.clear();
            return listColumns;
        }
        listColumns += stringColumn;
        // carry on
        n = pStatement->doFetch();
    }

    delete pStatement;
    return listColumns;
}

QStringList DATAWDataWidget::getColumns()
{
    QStringList listColumns;
    DATAStatement *pStatement = pConnection->getColumns( stringCatalog, stringSchema.isEmpty() ? QString() : stringSchema, stringTable );
    if ( !pStatement ) return listColumns;

    SQLRETURN n = pStatement->doFetch();
    while ( SQL_SUCCEEDED( n ) )
    {
        listColumns += pStatement->getData( 4 ).toString();
        // carry on
        n = pStatement->doFetch();
    }

    delete pStatement;
    return listColumns;
}

void DATAWDataWidget::doClear()
{
    nRows = 0;
    pStatement = 0;
    ptableResults->setColumnCount( 0 );
    ptableResults->setRowCount( 0 );
}

void DATAWDataWidget::doResultGUIGrid()
{
    SQLLEN  nRows;
    SWORD   nCols;

    // GET NUMBER OF ROWS AFFECTED
    // - the postgreSQL driver will always return -1 for result sets generated by the driver
    //   so lets try to get by without relying on SQLRowCount
    nRows = pStatement->getRowCount();

    // GET NUMBER OF COLUMNS RETURNED
    nCols = pStatement->getColumnCount();

    if ( nRows < 0 ) nRows = 0;
    if ( nCols < 0 ) nCols = 0;

    if ( nMaxRows > 0 ) ptableResults->setRowCount( qMin( (int)nRows, (int)nMaxRows ) );
    else ptableResults->setRowCount( nRows );

    ptableResults->setColumnCount( nCols );

    // GET A RESULTS HEADER (column headers)
    doResultGUIGridHeader( nCols );
    // GET A RESULTS BODY (data)
    if ( nCols > 0 ) doResultGUIGridBody( nCols );

    ptableResults->resize( this->size() );
    ptableResults->show();
}

void DATAWDataWidget::doResultGUIGridHeader( SWORD nColumns )
{
    int             nCol;
    QStringList     stringlistHeader;
    QVariant        v;

    for( nCol = 0; nCol < nColumns; nCol++ )
    {
        v = pStatement->getColAttribute( nCol+1, SQL_DESC_LABEL );
        stringlistHeader << v.toString();
    }

    ptableResults->setHorizontalHeaderLabels( stringlistHeader );
}

/*!
    doResultGUIGridBody

    Display the data part of results formatted in a GUI grid.
    
    NOTE: Do NOT rely upon SQLRowCount() as it often returns a misleading -1. For example
          when dealing with Driver generated result sets and other catalog type functions.
*/    
void DATAWDataWidget::doResultGUIGridBody( SWORD nColumns )
{
    SQLUSMALLINT    nCol                = 0;
    QVariant        v;

    // PROCESS ALL ROWS
    // we should be sure that we will not empty result set
    // othervise it will break SQLRowCount
    for( ; SQL_SUCCEEDED( pStatement->doFetch() ); )
    {
        // SOME DRIVERS DO NOT RETURN THE ROW COUNT PROPERLY SO EXPAND IF NEED BE 
        if ( ptableResults->rowCount() < nRows+1 )
            ptableResults->setRowCount( nRows+1 );

        // PROCESS ALL COLUMNS
        for( nCol = 0; nCol < nColumns; nCol++ )
        {
            v = pStatement->getData( nCol+1 );
            ptableResults->setItem( nRows, nCol, new QTableWidgetItem( v.toString() ) );
        }
        nRows++;
        if ( nMaxRows > 0 && nRows > nMaxRows )
        {
            emit signalMessage( "WARNING", "Results truncated." );
            break;
        }
    }
}

void DATAWDataWidget::doLoadState()
{
/*
    QSettings settings;
    QString stringPath( "/CBDSQLResultArea/Defaults/" );

    setMaxRows( settings.value( stringPath + "MaxRows", getMaxRows() ).toInt() );
*/
}

void DATAWDataWidget::doSaveState()
{
    // DO NOT replace the defaults here - it should only be done through a preferences dialog
}


